server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
  cloud:
   config:
     server:
       git:
         uri: https://github.com/coder-PengWenHao/Spring-Boot-Cloud-demos  # 配置git仓库的地址
         search-paths: config-repo
         username:
         password: